services:
  star-wars:
    image: 'java-performance:star-wars-1.0-SNAPSHOT'
    container_name: 'star-wars'
    restart: always
    environment:
      - 'JAVA_OPTS=-Xmx1024m'
      - 'logging.level.com.itachallenge=ERROR'
    ports:
      - "8763:8763"
    networks:
      grafana-net:
        ipv4_address: 173.18.0.2

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      grafana-net:
        ipv4_address: 173.18.0.3

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      grafana-net:
        ipv4_address: 173.18.0.4

volumes:
  grafana-data:

networks:
  grafana-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.18.0.0/24